# Generated by Django 3.0.4 on 2020-03-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valdata', '0003_auto_20200323_0206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VAConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('vcolor', models.CharField(max_length=255)),
                ('vsl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.Vessels')),
            ],
        ),
        migrations.CreateModel(
            name='AgentFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('filename', models.FileField(upload_to='')),
                ('uploaded_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('full', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('booking', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('carga', models.DecimalField(decimal_places=2, max_digits=20)),
                ('arrival', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('onhold', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity', models.CharField(blank=True, max_length=50, null=True)),
                ('haz', models.CharField(blank=True, max_length=50, null=True)),
                ('reefer', models.CharField(blank=True, max_length=10, null=True)),
                ('ondock', models.CharField(blank=True, max_length=1, null=True)),
                ('oog', models.CharField(blank=True, max_length=50, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agteam.VAConnector')),
                ('filefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agteam.AgentFILE')),
                ('pod', models.ForeignKey(on_delete=models.SET(1), to='valdata.PortName')),
                ('serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.Containers')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valdata.Vessels')),
            ],
        ),
    ]
