# Generated by Django 3.0.4 on 2020-03-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portname', '0001_initial'),
        ('agteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdata',
            name='pod',
            field=models.ForeignKey(on_delete=models.SET(1), to='portname.PortRegistry'),
        ),
    ]
