# Generated by Django 3.0.4 on 2020-03-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('schedule', '0002_vessels'),
        ('agteam', '0002_auto_20200326_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdata',
            name='serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Containers'),
        ),
        migrations.AlterField(
            model_name='agentdata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Vessels'),
        ),
        migrations.AlterField(
            model_name='vaconnector',
            name='vsl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Vessels'),
        ),
    ]
