# Generated by Django 3.0.4 on 2020-03-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnameA', models.CharField(max_length=30)),
                ('vnameB', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('portName', models.CharField(default='deltaport', max_length=30)),
                ('line', models.CharField(max_length=5)),
                ('service', models.CharField(max_length=5)),
                ('erdDate', models.DateTimeField(blank=True, null=True)),
                ('cutoffDate', models.DateTimeField(blank=True, null=True)),
                ('demurrageRFT', models.DateField(blank=True, null=True)),
                ('shipETAdate', models.DateField(blank=True, null=True)),
                ('shipETAtime', models.CharField(blank=True, max_length=10, null=True)),
                ('shipETDdate', models.DateTimeField(blank=True, null=True)),
                ('checkedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
