# Generated by Django 3.0.1 on 2020-01-21 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.FileField(upload_to='port/')),
                ('uploaded_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('serial', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('full', models.CharField(blank=True, max_length=10, null=True)),
                ('pod', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('booking', models.CharField(blank=True, max_length=20, null=True)),
                ('vessel', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('carga', models.DecimalField(decimal_places=2, max_digits=20)),
                ('arrival', models.CharField(blank=True, max_length=50, null=True)),
                ('onhold', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity', models.CharField(blank=True, max_length=50, null=True)),
                ('haz', models.CharField(blank=True, max_length=50, null=True)),
                ('reefer', models.CharField(blank=True, max_length=10, null=True)),
                ('ondock', models.CharField(blank=True, max_length=1, null=True)),
                ('oog', models.CharField(blank=True, max_length=50, null=True)),
                ('filefk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.PortFILE')),
            ],
        ),
    ]
