# Generated by Django 3.0.4 on 2020-03-21 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32)),
                ('ctype', models.CharField(max_length=32)),
                ('isActive', models.BooleanField(default=True)),
                ('lastUpdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=30, null=True)),
                ('pcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vessels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vslfull', models.CharField(max_length=30)),
                ('portName', models.CharField(max_length=30)),
                ('vcode', models.CharField(max_length=30)),
                ('vname', models.CharField(blank=True, max_length=30, null=True)),
                ('voyage', models.IntegerField()),
                ('line', models.CharField(max_length=5)),
                ('service', models.CharField(max_length=5)),
                ('erdDate', models.DateTimeField(blank=True, null=True)),
                ('cutoffDate', models.DateTimeField(blank=True, null=True)),
                ('demurrageRFT', models.DateField(blank=True, null=True)),
                ('shipETAdate', models.DateField(blank=True, null=True)),
                ('shipETAtime', models.CharField(blank=True, max_length=10, null=True)),
                ('shipETDdate', models.DateTimeField(blank=True, null=True)),
                ('checkedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPDConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('vcolor', models.CharField(max_length=255)),
                ('vsl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.Vessels')),
            ],
        ),
        migrations.CreateModel(
            name='PortFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.FileField(upload_to='port/')),
                ('uploaded_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('full', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('booking', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('carga', models.DecimalField(decimal_places=2, max_digits=20)),
                ('arrival', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('onhold', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity', models.CharField(blank=True, max_length=50, null=True)),
                ('haz', models.CharField(blank=True, max_length=50, null=True)),
                ('reefer', models.CharField(blank=True, max_length=10, null=True)),
                ('ondock', models.CharField(blank=True, max_length=1, null=True)),
                ('oog', models.CharField(blank=True, max_length=50, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valdata.VPDConnector')),
                ('filefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valdata.PortFILE')),
                ('pod', models.ForeignKey(on_delete=models.SET(1), to='valdata.PortName')),
                ('serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.Containers')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valdata.Vessels')),
            ],
        ),
        migrations.AddField(
            model_name='containers',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valdata.PortName'),
        ),
    ]
