# Generated by Django 3.0.4 on 2020-03-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessels',
            old_name='vcode',
            new_name='vslfulla',
        ),
        migrations.RenameField(
            model_name='vessels',
            old_name='vname',
            new_name='vslfullb',
        ),
        migrations.RemoveField(
            model_name='vessels',
            name='voyage',
        ),
        migrations.RemoveField(
            model_name='vessels',
            name='vslfull',
        ),
        migrations.AlterField(
            model_name='vessels',
            name='portName',
            field=models.CharField(default='deltaport', max_length=30),
        ),
    ]
