# Generated by Django 3.0.4 on 2020-03-20 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0002_auto_20200319_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containers',
            old_name='leftTo',
            new_name='pod',
        ),
        migrations.RenameField(
            model_name='containers',
            old_name='containerID',
            new_name='serial',
        ),
        migrations.RemoveField(
            model_name='containers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='vcolor',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='version',
        ),
        migrations.AddField(
            model_name='containers',
            name='lastUpdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VesselPortData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('vcolor', models.CharField(max_length=255)),
                ('prtdt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.PortData')),
                ('vsl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.Vessels')),
            ],
        ),
    ]
