# Generated by Django 3.0.4 on 2020-03-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0002_auto_20200323_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessels',
            old_name='vslfullb',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vessels',
            old_name='vslfulla',
            new_name='vnameA',
        ),
        migrations.AddField(
            model_name='vessels',
            name='vnameB',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
