# Generated by Django 3.0.4 on 2020-03-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portname', '0001_initial'),
        ('agteam', '0003_auto_20200326_2016'),
        ('inventory', '0001_initial'),
        ('schedule', '0002_vessels'),
        ('valdata', '0003_auto_20200323_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portdata',
            name='pod',
            field=models.ForeignKey(on_delete=models.SET(1), to='portname.PortRegistry'),
        ),
        migrations.AlterField(
            model_name='portdata',
            name='serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Containers'),
        ),
        migrations.AlterField(
            model_name='portdata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Vessels'),
        ),
        migrations.AlterField(
            model_name='vpdconnector',
            name='vsl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Vessels'),
        ),
        migrations.DeleteModel(
            name='Containers',
        ),
        migrations.DeleteModel(
            name='PortName',
        ),
        migrations.DeleteModel(
            name='Vessels',
        ),
    ]
